### ISSUE TITLE
Fallacy reporting is flawed

### ISSUE THREAD

**Issue by Changaco** [arguman/arguman.org#221]
- anyone can add a fallacy to any comment without justification
- the "accused" cannot respond
- the fallacies listed on a comment don't link to a definition of each one
- there is no way to remove fallacies

**Comment by fatiherikli** [comment]
- there is no way to remove fallacies`

This is resolved now.

**Comment by Restuta** [comment]
I second this issue

**Comment by Flushot** [comment]
I also agree with this issue, and have seen it abused in some arguments (such as [this one](http://en.arguman.org/react-is-mostly-hype/21836)). As it is now, the buck stops at a reported fallacy with no way of being able to defend the original position.

Why not be consistent with the rest of the design and make a fallacy node? That would allow a thread of rebuttal if the reported fallacy wasn't logically sound.

**Comment by raindropsfromsky** [comment]
There are several problems due to the structure:
1. The fallacies are embedded inside a node. This makes the node a complex statement with a built-in objection. That makes it impossible to make out whether the supporters are for the main node or for the fallacy.
2. While Arguman shows when a node was inserted, it does not record when a fallacy was pointed out. This makes it impossible to tell whether the supporters declared their support AFTER reading the fallacy, or were they unaware of the objection? Would they support the original node even now?
3. The structure does not allow anyone to point out that the reported fallacy is incorrect. We should not be allowed to simply delete a fallacy because we do not agree with it.
4. If more than one fallacies are embedded in a node, it is impossible to rebut any one fallacy independently. The visual graph simply cannot show this, because each node is supposed to have one simple proposition; not a complex argumentation.

Therefore, an easy solution is to define each fallacy as an independent "BUT" type node. where the fallacy is named, and the user inserts more text to justify how that fallacy label applies to the previous (rebutted) node.

For example, take [this](http://en.arguman.org/sexual-intercourse-before-marriage-is-immoral/12014) node. Instead of showing two embedded fallacies, the node can be refactored to show two separate BUT type nodes below it. Each "fallacy" node will identify who inserted it, and when. Now the graph can show number of supporters for each node; including people who support the view that there is a fallacy.

**Comment by iangilman** [comment]
I too am in favor of making fallacies real nodes that can be discussed; otherwise they are a form of  comment which is "above the law" and a vector for abuse. Here's me trying to work around the issue by using a "because" node to critique fallacies (in http://en.arguman.org/semi-colons-are-unnecessary-in-javascript):

<img width="264" alt="image" src="https://user-images.githubusercontent.com/338989/34423077-912ae6f0-ebce-11e7-83dd-407a3fccd9c8.png">

**Comment by iangilman** [comment]
Is this fixed now? It doesn't seem to be, but maybe the fix hasn't been deployed yet?
