### ISSUE TITLE
Request: Add fallacies

### ISSUE THREAD

**Issue by TrevorSayre** [arguman/arguman.org#253]
You currently link to the Wikipedia list of fallacies, but only allow the selection of a small number of these. For example, _Argumentum ad populum_ is not available for selection, but occurs frequently in software arguments.

Please either expand the provided list of fallacies or provide a way to input a custom fallacy.

**Comment by raindropsfromsky** [comment]
It is best to use Wikipedia's list, because-
 1 The Wikipedia list would grow with time. </br> &nbsp;&nbsp;&nbsp;To keep up with that, the local list would have to be updated from time to time.
 2 Wikipedia has more explanatory text (one page per fallacy).  </br> &nbsp;&nbsp;&nbsp;It also has interlinking and comparison between fallacies.  </br> &nbsp;&nbsp;&nbsp;It is impossible to replicate this in a local list.

**Comment by TrevorSayre** [comment]
That's fine so long as you use the full list
