### ISSUE TITLE
Provide a fallacy finder (find the matching fallacies that match the keywords that are being entered)

### ISSUE THREAD

**Issue by raindropsfromsky** [arguman/arguman.org#273]
Can we have a fallacy finder, where the workflow is this:
 1 The user types a few keywords to describe the error in logic, 
 2 The engine finds all matching fallacies, and lists them (name+description) </br> &nbsp; &nbsp; As the user enters more keywords, the list of matching fallacies becomes shorter.
 3 The user browses through the entries and selects one fallacy, and presses **_Enter**_
 4 The selected fallacy is accepted.

The workflow is just like how Bugzilla tries to find whether the bug is already raised, by showing all the bugs that contain the keywords that are being entered.

**Comment by raindropsfromsky** [comment]
Thanks for the rapid positive response!

Some more thoughts on how to implement:
 1 Can the engine also match synonyms of the keywords entered? (as in Google search).
 2 For this feature to work smoothly, the following changes are needed additionally:</br>&nbsp;&nbsp;&nbsp;(a) The in-built list of fallacies must be expanded drastically, and </br>&nbsp;&nbsp;&nbsp;(b) A ***Description*** field should be added.</br>&nbsp;&nbsp; Several people have requested this change, both at GitHub and also at [Arguman website](http://en.arguman.org/there-should-be-inbuilt-definitions-for-logical-fallacies-in-arguman).

**Comment by broofa** [comment]
Just stumbled across your arguman site.  Very cool!  And I landed here because the one really big pain point I encountered on using it as a first-time user was around this topic.

It seems like most, if not all, of the points being made have fallacies associated with them.  So the "add fallacy" feature is really compelling.  Unfortunately it's really hard to do right now.  The list of fallacies in the UI is, for most people, completely mystifying.  "Fallacy of the False Beard", "Is To Ought". "Slippery Slope"... these terms are, at best, only very loosely understood.  As a result, users are going to inevitably end up googling around trying to figure out WTF is meant, and which one should apply.  At least, that was certainly my experience.  I spent more time on google and wikipedia than I did on arguman.com.  :-/

Even a basic revamp of the UI without the keyword matching feature would be immensely helpful here. For example, if after selecting a fallacy type, a brief definition and example were shown so people didn't have to leave the site to google for the term.  Better still would be UI that let you navigate through the different types of fallacies to discover the correct one.  (The wikipedia page on fallacies you link to shows some of this structure)

Regardless, I think the goal of this feature request should be for arguman to present the possible fallacies in a way that is easily understood, and that pushes users toward a common understanding of what each type of fallacy means.

**Comment by raindropsfromsky** [comment]
Yes, just finding the name of the fallacy is not enough: There should be a built-in theoretical explanation for each name also. I found that the Logically fallacious book has the perfect format to explain each fallacy with multiple examples. (for example, see how it explains the [Ad Hominem](https://www.logicallyfallacious.com/tools/lp/Bo/LogicalFallacies/1/Ad_Hominem_Abusive) fallacy)
 
In fact, this book is an ideal companion for Arguman, because-
1. It provides a database of 300+ fallacies, which is not found in any other resource. 
2. Many of these fallacies are known by other names, which are also mentioned in the book.
3. The book also contains a [huge list](https://www.logicallyfallacious.com/tools/lp/Bo/LogicalFallacies/6/B_List_Fallacies) of "B-list fallacies" </br>(fallacies that are rarely seen, not really fallacies, or insignificant.) 
4. The book has an online version, and the readers can actually read it for free.
5. The online version invites the readers to submit even more fallacies, which will keep it at the cutting edge.

I suggest that we should start a wiki for Arguman, and link this book from there.
I can contribute in writing the wiki if anyone provides the engine.

**Comment by KrzysztofMadejski** [comment]
The downside for the book is that there is only English version I guess. I vote for having Wikipedia links. Relates to https://github.com/arguman/arguman.org/issues/234
